# Generated by Django 6.0.6 on 2026-06-29 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baralho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baralhos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=500)),
                ('resposta', models.CharField(max_length=500)),
                ('pontos', models.IntegerField(default=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cartas_img/')),
                ('baralho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='game.baralho')),
            ],
        ),
    ]
