# Generated by Django 6.0.6 on 2026-07-10 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baralho',
            name='publico',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('equipes_json', models.TextField()),
                ('vencedor', models.CharField(max_length=200)),
                ('baralho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='game.baralho')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
